### ISSUE TITLE
broken hyperlink in docs/install.rst

### ISSUE THREAD

**Issue by criverc** [opentaps/opentaps_seas#25]
https://volttron.readthedocs.io/en/develop/install.html   seems to be broken.

I checked the other links to public places in that file and they are ok.

**Comment by opentaps** [comment]
It should be https://volttron.readthedocs.io/en/develop/setup/index.html
I'll fix it.
-----
Si Chen
Open Source Strategies, Inc.

opentaps and open source business models
at the VOLTTRON conference: https://youtu.be/2jnyIOBHrkU
<http://bit.ly/2lUGmKm>


<https://youtu.be/3bBNcC3jnlc>
