### ISSUE TITLE
Typo in docs/deploy.rst

### ISSUE THREAD

**Issue by criverc** [opentaps/opentaps_seas#26]
The following patch fixes it:

    diff --git a/docs/deploy.rst b/docs/deploy.rst
    index 618d1ab..efe43b2 100644
    --- a/docs/deploy.rst
    +++ b/docs/deploy.rst
    @@ -33,7 +33,7 @@ Get Python from https://www.python.org/downloads/ and install it with::

     Make sure python is working by calling::

    -    /usr/locan/bin/python3.7 -v
    +    /usr/local/bin/python3.7 -v

**Comment by opentaps** [comment]
Sorry, what is different?  I can't tell from this.
-----
Si Chen
Open Source Strategies, Inc.

opentaps and open source business models
at the VOLTTRON conference: https://youtu.be/2jnyIOBHrkU
<http://bit.ly/2lUGmKm>


<https://youtu.be/3bBNcC3jnlc>

**Comment by criverc** [comment]
I am sorry, the path is wrong, it says /usr/locan it should be /usr/local

**Comment by opentaps** [comment]
Fixed!  Thanks again for pointing that out.
-----
Si Chen
Open Source Strategies, Inc.

opentaps and open source business models
at the VOLTTRON conference: https://youtu.be/2jnyIOBHrkU
<http://bit.ly/2lUGmKm>


<https://youtu.be/3bBNcC3jnlc>
