### ISSUE TITLE
Site/Device Overlap

### ISSUE THREAD

**Issue by acedrew** [opentaps/opentaps_seas#34]
When viewing a site, if a site has  device ID that is also present in another site, the description displayed is from the first site in the database, vs the site you're viewing.

![image](https://user-images.githubusercontent.com/977415/69738626-6e856a00-1104-11ea-9485-cefa75823005.png)

**Comment by rybalko** [comment]
Andrew, can you please say me where this wrong device_id/description is on your screenshot ?

**Comment by acedrew** [comment]
Sorry, yes, the device id 100 is description/name is not "Firing Range", it appears that site_name is not included in the query populating the descriptions/names, so it's returning the first one it finds, which is for a different site. From what I can tell everything else is correct, just the incorrect description/name

**Comment by rybalko** [comment]
Andrew, can you please get latest changes and try it ?

**Comment by acedrew** [comment]
Looks like that fixed it! Running aafb67eb3e38b807499f23cbee662eea2d04798f  and it appears to be resolved.
